"""add cert

Revision ID: 4515f35e73c0
Revises: fcc5477dcc55
Create Date: 2025-03-16 18:16:15.468784

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4515f35e73c0'
down_revision = 'fcc5477dcc55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate',
    sa.Column('certificate_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('institution', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issue_date', sa.DateTime(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificate_certificate_name'), 'certificate', ['certificate_name'], unique=False)
    op.create_index(op.f('ix_certificate_institution'), 'certificate', ['institution'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_certificate_institution'), table_name='certificate')
    op.drop_index(op.f('ix_certificate_certificate_name'), table_name='certificate')
    op.drop_table('certificate')
    # ### end Alembic commands ###
