"""update_education_table

Revision ID: 457602f49673
Revises: e73029a3b2a7
Create Date: 2025-03-16 14:18:35.857532

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '457602f49673'
down_revision = 'e73029a3b2a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('education', sa.Column('qualification', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('education', sa.Column('institution', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('education', sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('education', sa.Column('graduation_year', sa.Integer(), nullable=False))
    op.add_column('education', sa.Column('minor', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('education', sa.Column('gpa', sa.Float(), nullable=True))
    op.add_column('education', sa.Column('additional_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('education', 'degree',
               existing_type=sa.VARCHAR(length=100),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=False)
    op.drop_column('education', 'school')
    op.drop_column('education', 'start_date')
    op.drop_column('education', 'end_date')
    op.drop_column('education', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('education', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('education', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('education', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('education', sa.Column('school', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('education', 'degree',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('education', 'additional_info')
    op.drop_column('education', 'gpa')
    op.drop_column('education', 'minor')
    op.drop_column('education', 'graduation_year')
    op.drop_column('education', 'location')
    op.drop_column('education', 'institution')
    op.drop_column('education', 'qualification')
    # ### end Alembic commands ###
