"""update course work

Revision ID: 81758446daf2
Revises: 4515f35e73c0
Create Date: 2025-03-16 18:58:51.096065

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '81758446daf2'
down_revision = '4515f35e73c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coursework',
    sa.Column('course_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('institution', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('completion_date', sa.DateTime(), nullable=False),
    sa.Column('skill_learned', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('skill_application', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coursework_course_name'), 'coursework', ['course_name'], unique=False)
    op.create_index(op.f('ix_coursework_institution'), 'coursework', ['institution'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coursework_institution'), table_name='coursework')
    op.drop_index(op.f('ix_coursework_course_name'), table_name='coursework')
    op.drop_table('coursework')
    # ### end Alembic commands ###
